name: build_macos
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build_macos:
    name: Build MacOS
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Link libgomp.a
        run: |
          sudo ln -s /usr/local/lib/gcc/10/libgomp.a /usr/local/lib/libgomp.a
      - name: Install dependencies
        run: |
          brew install octave
      - name: Update RCS keywords
        run: |
          printf '\n[filter "rcs-keywords"]\n\tclean  = .git_filters/rcs-keywords.clean\n\tsmudge = .git_filters/rcs-keywords.smudge %f\n' >> .git/config
          rm -rf src/*.c
          git checkout src/*.c
      - name: Build mmclab for Octave
        run: |
          cd src
          make oct CC=gcc-10 CXX=g++-10 USEROCTOPT="CXXFLAGS='-pipe -Os -arch x86_64' DL_LD=g++ DL_LDFLAGS='-fopenmp -static-libgcc -static-libstdc++'"
          otool -L ../mmclab/mmc.mex
      - name: Build binary
        run: |
          cd src
          make clean
          make CC=gcc-10 CXX=g++-10
          otool -L bin/mmc
      - name: Upload mmclab package
        if: ${{ runner.name == 'macos-10.15' }}
        uses: actions/upload-artifact@v3
        with:
          name: mmclab-macos-x64_64-${{ github.ref_name }}
          path: mmclab
      - name: Create package folder
        run: |
          mkdir packages
      - name: Zip mmclab
        run: |
          zip -FSr --symlink packages/mmclab-macos-x64_64-${{ github.ref_name }}.zip mmclab
      - name: Prepare mmc package
        run: |
          mv src/bin .
          rm -rf .git mmclab webmmc commons src .git_filters .gitattributes .github .travis.yml win32 deploy
          mkdir -p src/bin
          cd src/bin
          ln -s ../../bin/mmc .
          cd ../../
      - name: Upload mmc package
        if: ${{ runner.name == 'macos-10.15' }}
        uses: actions/upload-artifact@v3
        with:
          name: mmc-macos-x64_64-${{ github.ref_name }}
          path: .
      - name: Zip mmc
        run: |
          zip -FSr --symlink packages/mmc-macos-x64_64-${{ github.ref_name }}.zip . -x packages
      - name: Copy package to server
        if: ${{ runner.name == 'macos-10.15' && github.repository_owner == 'fangq' && github.event_name != 'pull_request'}}
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.MCX_SERVER }}
          username: ${{ secrets.MCX_SERVER_USER }}
          ssh_private_key: ${{ secrets.MCX_SERVER_SSH_KEY }}
          local_path: "packages/*"
          remote_path: "fanglab/mcx.space/nightly/github"
