name: build_macos
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build_macos:
    name: Build MacOS
    runs-on: macos-10.15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          brew install octave
      - name: Update RCS keywords
        shell: bash
        run: |
          printf '\n[filter "rcs-keywords"]\n\tclean  = .git_filters/rcs-keywords.clean\n\tsmudge = .git_filters/rcs-keywords.smudge %f\n' >> .git/config
          rm -rf src/*.c
          git checkout src/*.c
      - name: Get current date
        id: date
        run: echo "RELEASE_VERSION=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Build mmclab for Octave
        shell: bash
        run: |
          cd src
          make oct USEROCTOPT="CXXFLAGS='-pipe -Os -arch x86_64' DL_LD=g++ DL_LDFLAGS='-fopenmp -static-libgcc -static-libstdc++'"
      - name: Build binary
        shell: bash
        run: |
          cd src
          make clean
          make
      - name: Upload mmclab package
        uses: actions/upload-artifact@v3
        with:
          name: mmclab-macos-x64_64-${{ env.RELEASE_VERSION }}
          path: mmclab
      - name: Prepare mmc package
        shell: bash
        run: |
          mv src/bin .
          rm -rf .git mmclab webmmc commons src .git_filters .gitattributes .github .travis.yml win32 deploy
          mkdir -p src/bin
          cd src/bin
          ln -s ../../bin/mmc .
          cd ../../
      - name: Upload mmc package
        uses: actions/upload-artifact@v3
        with:
          name: mmc-macos-x64_64-${{ env.RELEASE_VERSION }}
          path: .
