name: build_win64
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build_win64:
    name: Build Win64
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          choco install octave.install
      - name: Update RCS keywords
        shell: bash
        run: |
          printf '\n[filter "rcs-keywords"]\n\tclean  = .git_filters/rcs-keywords.clean\n\tsmudge = .git_filters/rcs-keywords.smudge %f\n' >> .git/config
          rm -rf src/*.c
          git checkout src/*.c
      - name: Get current date
        id: date
        run: echo "RELEASE_VERSION=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Build mmclab for Octave
        shell: bash
        run: |
          cd src
          make oct LIBOPENCL='/c/Windows/System32/OpenCL.dll'
      - name: Build binary
        shell: bash
        run: |
          cd src
          make clean
          make USERARFLAGS="libzmat.a -lz"
      - name: Upload mmclab package
        uses: actions/upload-artifact@v3
        with:
          name: mmclab-win64-x64_64-${{ env.RELEASE_VERSION }}
          path: mmclab
      - name: Prepare mmc package
        shell: bash
        run: |
          mv src/bin .
          rm -rf .git mmclab webmmc commons src .git_filters .gitattributes .github .travis.yml win32 deploy
          mkdir -p src/bin
          cd src/bin
          cmd /c "mklink /h mmc.exe ..\..\bin\mmc.exe"
          cd ../../
      - name: Upload mmc package
        uses: actions/upload-artifact@v3
        with:
          name: mmc-win64-x64_64-${{ env.RELEASE_VERSION }}
          path: .
