name: build_win64
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build_win64:
    name: Build Win64
    runs-on: windows-2019
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        shell: pwsh
        run: |
          #choco install octave.portable --version=5.2.0
          #echo 'C:\ProgramData\chocolatey\lib\octave.portable\tools\octave\mingw64\bin' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo 'C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install OpenCL.dll and static libraries
        run: |
          mkdir opencl
          cd opencl
          curl http://mcx.space/wiki/upload/opencl.zip --output opencl.zip
          unzip opencl.zip
          cp bin/OpenCL.dll 'c:\Windows\System32'
          cd ..
          rm -rf opencl
      - name: Update RCS keywords
        run: |
          printf '\n[filter "rcs-keywords"]\n\tclean  = .git_filters/rcs-keywords.clean\n\tsmudge = .git_filters/rcs-keywords.smudge %f\n' >> .git/config
          rm -rf src/*.c
          git checkout src/*.c
      - name: Get current date
        id: date
        run: echo "RELEASE_VERSION=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      #- name: Build mmclab for Octave
      #  run: |
      #    cd src
      #    which gcc
      #    gcc -v
      #    make oct CC=gcc CXX=g++ LIBOPENCL='/c/Windows/System32/OpenCL.dll --verbose'
      - name: Build binary
        run: |
          cd src
          which gcc
          gcc -v
          make clean
          make CC=gcc CXX=g++ USERARFLAGS="-Lc:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32/lib -Lc:/ghcup/ghc/9.0.2/mingw/lib -Lc:/ghcup/ghc/9.0.2/mingw/x86_64-w64-mingw32/lib libzmat.a -lz -lssp"
      - name: Upload mmclab package
        uses: actions/upload-artifact@v3
        with:
          name: mmclab-win64-x64_64-${{ env.RELEASE_VERSION }}
          path: mmclab
      - name: Prepare mmc package
        run: |
          mv src/bin .
          rm -rf .git mmclab webmmc commons src .git_filters .gitattributes .github .travis.yml win32 deploy
          mkdir -p src/bin
          cd src/bin
          cmd /c "mklink /h mmc.exe ..\..\bin\mmc.exe"
          cd ../../
      - name: Upload mmc package
        uses: actions/upload-artifact@v3
        with:
          name: mmc-win64-x64_64-${{ env.RELEASE_VERSION }}
          path: .
